name: 'phplint'
description: 'test phplint'

runs:
  using: "composite"
  steps:

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: entrypoint.sh
      shell: bash